import type { ThemeConfig } from "antd";

export const reportTheme: ThemeConfig = {
  token: {
    colorPrimary: "#15803D",
    colorPrimaryHover: "#16A34A",
    colorPrimaryActive: "#166534",
    colorLink: "#15803D",
    colorLinkHover: "#166534",
    colorLinkActive: "#14532D",
    colorText: "#1F2329",
    colorTextSecondary: "#646A73",
    colorTextTertiary: "#8F959E",
    colorBgLayout: "#F4F5F7",
    colorBgContainer: "#FFFFFF",
    colorFillAlter: "#F7F8FA",
    colorFillTertiary: "#F1F2F4",
    colorBorder: "#DADDE1",
    colorBorderSecondary: "#E8E9EB",
    controlHeight: 28,
    borderRadius: 6,
    borderRadiusLG: 6,
    fontSize: 14,
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
    lineHeight: 1.5714285714285714,
    controlOutline: "rgba(21, 128, 61, 0.24)",
    boxShadowTertiary: "0 1px 3px rgba(31, 35, 41, 0.08)",
  },
  components: {
    Button: {
      fontWeight: 500,
      primaryColor: "#FFFFFF",
      primaryShadow: "none",
      defaultShadow: "none",
      dangerShadow: "none",
      defaultColor: "#1F2329",
      defaultBorderColor: "#DADDE1",
      defaultHoverBg: "#F0FDF4",
      defaultHoverColor: "#166534",
      defaultHoverBorderColor: "#22C55E",
      defaultActiveBg: "#DCFCE7",
      defaultActiveColor: "#14532D",
      defaultActiveBorderColor: "#166534",
      textTextHoverColor: "#166534",
      textTextActiveColor: "#14532D",
    },
    Card: {
      bodyPadding: 12,
      bodyPaddingSM: 12,
      headerHeight: 48,
      headerHeightSM: 40,
      headerPadding: 12,
      headerPaddingSM: 12,
      headerFontSize: 16,
      headerFontSizeSM: 14,
    },
    Input: {
      hoverBorderColor: "#22C55E",
      activeBorderColor: "#166534",
      activeShadow: "0 0 0 2px rgba(21, 128, 61, 0.18)",
      hoverBg: "#F7FEF9",
      activeBg: "#FFFFFF",
    },
    Layout: {
      bodyBg: "#F4F5F7",
      headerBg: "#FFFFFF",
      headerHeight: 56,
      headerPadding: "0 16px",
      siderBg: "#FFFFFF",
      lightSiderBg: "#FFFFFF",
    },
    Menu: {
      itemHeight: 40,
      itemMarginBlock: 2,
      itemMarginInline: 8,
      itemPaddingInline: 12,
      itemBorderRadius: 4,
      subMenuItemBorderRadius: 4,
      itemColor: "#424750",
      itemHoverColor: "#166534",
      itemHoverBg: "#F0FDF4",
      itemActiveBg: "#DCFCE7",
      itemSelectedColor: "#166534",
      itemSelectedBg: "#DCFCE7",
      subMenuItemSelectedColor: "#166534",
      activeBarWidth: 0,
    },
    Pagination: {
      itemSize: 28,
      itemSizeSM: 24,
      itemActiveBg: "#DCFCE7",
      itemActiveColor: "#166534",
      itemActiveColorHover: "#14532D",
    },
    Select: {
      hoverBorderColor: "#22C55E",
      activeBorderColor: "#166534",
      activeOutlineColor: "rgba(21, 128, 61, 0.18)",
      optionActiveBg: "#F0FDF4",
      optionSelectedBg: "#DCFCE7",
      optionSelectedColor: "#14532D",
      selectorBg: "#F7F8FA",
    },
    Table: {
      headerBg: "#F7F8FA",
      headerColor: "#30343B",
      headerSortActiveBg: "#DCFCE7",
      headerSortHoverBg: "#F0FDF4",
      bodySortBg: "#F7FEF9",
      rowHoverBg: "#F0FDF4",
      rowSelectedBg: "#DCFCE7",
      rowSelectedHoverBg: "#BBF7D0",
      cellPaddingBlockSM: 8,
      cellPaddingInlineSM: 10,
      cellFontSizeSM: 14,
      borderColor: "#E8E9EB",
      headerSplitColor: "#DADDE1",
      headerBorderRadius: 0,
      footerBg: "#F0FDF4",
      footerColor: "#1F2329",
    },
    Tabs: {
      inkBarColor: "#15803D",
      itemHoverColor: "#166534",
      itemActiveColor: "#14532D",
      itemSelectedColor: "#166534",
      titleFontSize: 14,
    },
  },
};
